version: '3'
services:
  firefox:
    image: selenium/node-firefox:3.8.1-erbium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.8.1-erbium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.8.1-erbium
    environment:
      GRID_BROWSER_TIMEOUT: 60
    ports:
      - "4444:4444"

  uptime_monitor:
    build: .
    volumes:
      - .:/usr/src/uptime_monitor
    depends_on:
      - firefox
      - chrome
    links:
      - hub:hub
    environment:
      S3_AWS_ACCESS_KEY_ID:
      S3_AWS_SECRET_ACCESS_KEY:
      RAGIOS_HERCULES_S3_DIR:
      RAGIOS_HERCULES_ENABLE_SCREENSHOTS:
      HUB_HOST: hub
      HUB_PORT: 4444
    entrypoint: bundle exec rake repl

  unit_tests:
    build: .
    volumes:
      - .:/usr/src/uptime_monitor
    depends_on:
      - firefox
    links:
      - hub:hub
    environment:
      S3_AWS_ACCESS_KEY_ID:
      S3_AWS_SECRET_ACCESS_KEY:
      RAGIOS_HERCULES_S3_DIR:
      RAGIOS_HERCULES_ENABLE_SCREENSHOTS:
      HUB_HOST: hub
      HUB_PORT: 4444
    entrypoint: bundle exec rspec -fd spec
