# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: uptime_monitor 0.7.8 ruby lib

Gem::Specification.new do |s|
  s.name = "uptime_monitor".freeze
  s.version = "0.7.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["obi-a".freeze]
  s.date = "2018-10-06"
  s.description = "A Ragios plugin that uses a real web browser to monitor transactions on a website for availability".freeze
  s.email = "obioraakubue@yahoo.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".env.examples",
    ".travis.yml",
    "Dockerfile",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "docker-compose.yml",
    "lib/uptime_monitor.rb",
    "lib/uptime_monitor/browser.rb",
    "lib/uptime_monitor/browsers.treetop",
    "lib/uptime_monitor/maestro.treetop",
    "lib/uptime_monitor/maestro_broswer.rb",
    "lib/uptime_monitor/parser.rb",
    "lib/uptime_monitor/screen_shot_uploader.rb",
    "lib/uptime_monitor/uptime_monitor.rb",
    "spec/browser_spec.rb",
    "spec/browsers_lang_parser_spec.rb",
    "spec/maestro_lang_parser_spec.rb",
    "spec/spec_helper.rb",
    "spec/uptime_monitor_spec.rb",
    "uptime_monitor.gemspec"
  ]
  s.homepage = "http://github.com/obi-a/uptime_monitor".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.13".freeze
  s.summary = "Real browser website uptime monitoring plugin for Ragios".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<watir>.freeze, ["~> 6.14.0"])
      s.add_runtime_dependency(%q<watir-webdriver-performance>.freeze, ["~> 0.2.4"])
      s.add_runtime_dependency(%q<aws-s3>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<treetop>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.7"])
      s.add_development_dependency(%q<pry>.freeze, [">= 0"])
    else
      s.add_dependency(%q<watir>.freeze, ["~> 6.14.0"])
      s.add_dependency(%q<watir-webdriver-performance>.freeze, ["~> 0.2.4"])
      s.add_dependency(%q<aws-s3>.freeze, [">= 0"])
      s.add_dependency(%q<treetop>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.7"])
      s.add_dependency(%q<pry>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<watir>.freeze, ["~> 6.14.0"])
    s.add_dependency(%q<watir-webdriver-performance>.freeze, ["~> 0.2.4"])
    s.add_dependency(%q<aws-s3>.freeze, [">= 0"])
    s.add_dependency(%q<treetop>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.7"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
  end
end

